### ISSUE TITLE
Errors with rdoc 6.0.2

### ISSUE THREAD

**Issue by dpogue** [zzak/sdoc#124]
Latest version of rdoc seems to be causing some weird templating errors:

```
$ ./bin/rails rdoc

Parsing sources...
100% [35/35]  lib/mygem/version.rb                                           

Generating SDoc format into /Users/dpogue/Coding/mygem/doc...
rails aborted!
RDoc::Error: Error while evaluating /Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/_context.rhtml: undefined method `rdoc' for nil:NilClass (at "pan class=\"type\">MODULE</span>\n          <a href=\"")
```

<details><summary>Full error</summary>

```
RDoc::Error: Error while evaluating /Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/_context.rhtml: undefined method `rdoc' for nil:NilClass (at "pan class=\"type\">MODULE</span>\n          <a href=\"")
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:28:in `eval'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/_context.rhtml:39:in `block in include_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/_context.rhtml:36:in `each'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/_context.rhtml:36:in `include_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:13:in `eval_template'
(eval):1:in `include_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:28:in `eval'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:28:in `include_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/file.rhtml:32:in `block in generate_file_files'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:13:in `eval_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:35:in `render_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/generator.rb:146:in `block in generate_file_files'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/generator.rb:140:in `each'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/generator.rb:140:in `generate_file_files'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/generator.rb:92:in `generate'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/rdoc.rb:528:in `block in generate'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/rdoc.rb:523:in `chdir'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/rdoc.rb:523:in `generate'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/rdoc.rb:502:in `document'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/task.rb:248:in `block in define'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/command.rb:46:in `invoke'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/engine/commands.rb:7:in `require'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/engine/commands.rb:7:in `<top (required)>'
./bin/rails:13:in `require'
./bin/rails:13:in `<main>'

Caused by:
NoMethodError: undefined method `rdoc' for nil:NilClass
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:28:in `eval'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/_context.rhtml:39:in `block in include_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/_context.rhtml:36:in `each'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/_context.rhtml:36:in `include_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:13:in `eval_template'
(eval):1:in `include_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:28:in `eval'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:28:in `include_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/rdoc/generator/template/rails/file.rhtml:32:in `block in generate_file_files'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:13:in `eval_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:35:in `render_template'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/generator.rb:146:in `block in generate_file_files'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/generator.rb:140:in `each'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/generator.rb:140:in `generate_file_files'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/sdoc-1.0.0/lib/sdoc/generator.rb:92:in `generate'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/rdoc.rb:528:in `block in generate'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/rdoc.rb:523:in `chdir'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/rdoc.rb:523:in `generate'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/rdoc.rb:502:in `document'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/rdoc-6.0.2/lib/rdoc/task.rb:248:in `block in define'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/command.rb:46:in `invoke'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/engine/commands.rb:7:in `require'
/Users/dpogue/.rvm/gems/ruby-2.3.4@mygem/gems/railties-5.1.5/lib/rails/engine/commands.rb:7:in `<top (required)>'
./bin/rails:13:in `require'
./bin/rails:13:in `<main>'
Tasks: TOP => rdoc => doc/created.rid
(See full trace by running task with --trace)
```

</details>

I downgraded to rdoc 6.0.1 and it worked as expected. I don't see a changelog for rdoc 6.0.2, so I don't have any hints at the moment for what is to blame.

**Comment by robin850** [comment]
This is most-likely an RDoc issue ; ruby/rdoc#614 has been opened to try to fix this problem. We can reopen if I'm totally wrong and the problem comes from here but for now, we can close this. Thanks for reporting @dpogue !

**Comment by robin850** [comment]
(Just for the record, the aforementioned pull request has been merged so this issue shouldn't be present anymore with the release of RDoc 6.0.4)
