### ISSUE TITLE
uninitialized constant Rake::RDocTask

### ISSUE THREAD

**Issue by cheshire137** [zzak/sdoc#89]
I have this in my Gemfile: `gem 'sdoc', '~> 0.4.1', group: :doc` and the following as a Rake task in my Rails 4 app:

```ruby
require 'sdoc'

Rake::RDocTask.new do |rdoc|
  rdoc.main = 'README.md'
  rdoc.rdoc_files.include('README.md', 'app/**/*.rb', 'lib/*.rb', 'config/**/*.rb')
  rdoc.template = 'direct' # lighter template used on railsapi.com
  rdoc.options << '--all'
  rdoc.title = 'My Documentation'
end
```

I got this Rake task code from the sdoc README.

Just doing `bin/rake -T` results in the following error: 

```
rake aborted!
NameError: uninitialized constant Rake::RDocTask
/my_app/lib/tasks/documentation.rake:3:in `<top (required)>'
/var/lib/gems/2.1.0/gems/railties-4.2.2/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.2/lib/rails/engine.rb:658:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.2/lib/rails/engine.rb:658:in `run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.2/lib/rails/application.rb:452:in `run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.2/lib/rails/engine.rb:453:in `load_tasks'
```

**Comment by motine** [comment]
after a little fumbling, I found this to work:

```ruby
require "rdoc/task"
require 'sdoc'

Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = 'doc/api'
  rdoc.generator = 'sdoc'
  rdoc.template = 'rails' # change default from 'sdoc' to 'rails' style
end
```

Please update the documentation.

**Comment by zzak** [comment]
@cheshire137 @motine Thank you for your report and investigation!

I ran into this too myself, and fixed the documentation :)

**Comment by motine** [comment]
thanks for the quick patch.
